### ISSUE TITLE
Getting: uninitialized constant CDQ::CDQConfig::YAML error after bundle update

### ISSUE THREAD

**Issue by matthewsinclair** [infinitered/redpotion#137]
I just ran a `bundle update` on my RedPotion project and got the following CDQ error:

```
*** Starting simulator
(main)> 2015-08-01 12:00:02.422 Pendulum[57525:536800] config.rb:38:in `block in initialize:': uninitialized constant CDQ::CDQConfig::YAML (NameError)
	from config.rb:38:in `initialize:'
	from config.rb:94:in `default'
	from model.rb:9:in `initialize:'
	from object.rb:17:in `models'
	from object.rb:13:in `stores'
	from object.rb:9:in `contexts'
	from object.rb:55:in `setup:'
	from app_delegate.rb:8:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-08-01 12:00:02.434 Pendulum[57525:536800] *** Terminating app due to uncaught exception 'NameError', reason: 'config.rb:38:in `block in initialize:': uninitialized constant CDQ::CDQConfig::YAML (NameError)
	from config.rb:38:in `initialize:'
	from config.rb:94:in `default'
	from model.rb:9:in `initialize:'
	from object.rb:17:in `models'
	from object.rb:13:in `stores'
	from object.rb:9:in `contexts'
	from object.rb:55:in `setup:'
	from app_delegate.rb:8:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010473fc65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000100b62bb7 objc_exception_throw + 45
	2   Pendulum                            0x000000010053647f _ZL10__vm_raisev + 399
	3   Pendulum                            0x00000001005365ad rb_vm_raise + 205
	4   Pendulum                            0x00000001004334a9 rb_exc_raise + 9
	5   Pendulum                            0x000000010042d754 rb_name_error + 228
	6   Pendulum                            0x00000001004e55e9 rb_mod_const_missing + 121
	7   Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	8   Pendulum                            0x00000001004e64fd rb_const_get_0 + 1165
	9   Pendulum                            0x000000010005be4e vm_get_const + 302
	10  Pendulum                            0x00000001001573dc rb_scope__initialize:__block__ + 92
	11  Pendulum                            0x0000000100508fef _ZL13vm_block_evalP7RoxorVMP11rb_vm_blockP13objc_selectormiPKm + 1119
	12  Pendulum                            0x0000000100509310 rb_vm_yield_args + 64
	13  Pendulum                            0x00000001004fcdcb rb_yield + 59
	14  Pendulum                            0x0000000100536789 rb_ensure + 25
	15  Pendulum                            0x0000000100507775 rb_vm_dispatch + 5925
	16  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	17  Pendulum                            0x000000010015679e rb_scope__initialize:__ + 686
	18  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	19  Pendulum                            0x00000001004670e4 rb_class_new_instance0 + 884
	20  Pendulum                            0x0000000100507775 rb_vm_dispatch + 5925
	21  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	22  Pendulum                            0x0000000100158493 rb_scope__default__ + 387
	23  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	24  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	25  Pendulum                            0x00000001001666ea rb_scope__initialize:__ + 186
	26  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	27  Pendulum                            0x00000001004670e4 rb_class_new_instance0 + 884
	28  Pendulum                            0x0000000100507775 rb_vm_dispatch + 5925
	29  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	30  Pendulum                            0x0000000100171be9 rb_scope__models__ + 153
	31  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	32  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	33  Pendulum                            0x0000000100171a8b rb_scope__stores__ + 187
	34  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	35  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	36  Pendulum                            0x000000010017190b rb_scope__contexts__ + 187
	37  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	38  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	39  Pendulum                            0x0000000100172346 rb_scope__setup:__ + 614
	40  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	41  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	42  Pendulum                            0x00000001003bd673 rb_scope__on_load:__ + 163
	43  Pendulum                            0x0000000100507d39 rb_vm_dispatch + 7401
	44  Pendulum                            0x000000010005c4ac vm_dispatch + 1436
	45  Pendulum                            0x000000010030c8da rb_scope__application:didFinishLaunchingWithOptions:__ + 202
	46  Pendulum                            0x000000010030cadd __unnamed_46 + 61
	47  UIKit                               0x0000000102536748 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 240
	48  UIKit                               0x0000000102537357 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2540
	49  UIKit                               0x000000010253a19e -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
	50  UIKit                               0x0000000102539095 -[UIApplication workspaceDidEndTransaction:] + 179
	51  FrontBoardServices                  0x0000000108e0f5e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	52  CoreFoundation                      0x000000010467341c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	53  CoreFoundation                      0x0000000104669165 __CFRunLoopDoBlocks + 341
	54  CoreFoundation                      0x0000000104668f25 __CFRunLoopRun + 2389
	55  CoreFoundation                      0x0000000104668366 CFRunLoopRunSpecific + 470
	56  UIKit                               0x0000000102538b02 -[UIApplication _run] + 413
	57  UIKit                               0x000000010253b8c0 UIApplicationMain + 1282
	58  Pendulum                            0x00000001000648cf main + 111
	59  libdyld.dylib                       0x0000000107201145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NameError
```

The project is pretty standard. Here's the `gemfile`:

```
source "https://rubygems.org"
gem "rake"
gem "motion-cocoapods"
gem "redpotion"
gem "cdq"
gem "afmotion"
gem "newclear" 
gem "ProMotion-form"
gem "ProMotion-push", "~> 0.2"
gem "ProMotion-map", "~> 0.3"
gem "ProMotion-iap"
gem "ProMotion-menu"
gem "bubble-wrap"
gem 'motion-blitz'
```

Any ideas?

**Comment by matthewsinclair** [comment]
Fixed as per: https://github.com/infinitered/cdq/issues/112
