### ISSUE TITLE
Refreshable TableView Crash On Example App

### ISSUE THREAD

**Issue by zhigang1992** [infinitered/redpotion#82]
```
(main)> 2015-04-18 20:29:19.546 RedPotion[53366:624352] refreshable.rb:41:in `refreshView:': undefined local variable or method `refreshable_callback' for #<ContributerScreen:0x1
0b4b7a60> (NameError)
2015-04-18 20:29:19.551 RedPotion[53366:624352] *** Terminating app due to uncaught exception 'NameError', reason: 'refreshable.rb:41:in `refreshView:': undefined local variable
or method `refreshable_callback' for #<ContributerScreen:0x10b4b7a60> (NameError)
'
*** First throw call stack:
(
        0   CoreFoundation                      0x00000001031e9c65 __exceptionPreprocess + 165
        1   libobjc.A.dylib                     0x0000000100714bb7 objc_exception_throw + 45
        2   RedPotion                           0x0000000100348caf _ZL10__vm_raisev + 399
        3   RedPotion                           0x0000000100348ddd rb_vm_raise + 205
        4   RedPotion                           0x0000000100246ee9 rb_exc_raise + 9
        5   RedPotion                           0x0000000100347052 rb_vm_method_missing + 786
        6   RedPotion                           0x0000000100319f85 rb_vm_dispatch + 5925
        7   RedPotion                           0x000000010031871d rb_vm_trigger_method_missing + 1053
        8   RedPotion                           0x000000010031997f rb_vm_dispatch + 4383
        9   RedPotion                           0x000000010001ed7c vm_dispatch + 1436
        10  RedPotion                           0x00000001001c530d rb_scope__refreshView:__ + 381
        11  RedPotion                           0x00000001001c5608 __unnamed_25 + 40
        12  UIKit                               0x0000000100c38da2 -[UIApplication sendAction:to:from:forEvent:] + 75
        13  UIKit                               0x0000000100d4a54a -[UIControl _sendActionsForEvents:withEvent:] + 467
        14  UIKit                               0x000000010131aaf5 -[UIRefreshControl _setRefreshControlState:notify:] + 318
        15  libdispatch.dylib                   0x000000010473af16 _dispatch_call_block_and_release + 12
        16  libdispatch.dylib                   0x0000000104755964 _dispatch_client_callout + 8
        17  libdispatch.dylib                   0x000000010473f50c _dispatch_after_timer_callback + 89
        18  libdispatch.dylib                   0x0000000104755964 _dispatch_client_callout + 8
        19  libdispatch.dylib                   0x000000010474c1e2 _dispatch_source_latch_and_call + 786
        20  libdispatch.dylib                   0x00000001047454a0 _dispatch_source_invoke + 404
        21  libdispatch.dylib                   0x0000000104740927 _dispatch_main_queue_callback_4CF + 398
        22  CoreFoundation                      0x00000001031511f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
        23  CoreFoundation                      0x0000000103112dcb __CFRunLoopRun + 2043
        24  CoreFoundation                      0x0000000103112366 CFRunLoopRunSpecific + 470
        25  GraphicsServices                    0x0000000104ffda3e GSEventRunModal + 161
        26  UIKit                               0x0000000100c37900 UIApplicationMain + 1282
        27  RedPotion                           0x0000000100026e5f main + 111
        28  libdyld.dylib                       0x0000000104785145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NameError

================================================================================
The application terminated. A crash report file may have been generated by the
system, use `rake crashlog' to open it. Use `rake debug=1' to restart the app
in the debugger.
================================================================================
```

Steps to reproduce:
1. Open Example App.
2. Click Data Table Screen.
3. Pull To Refresh.
4. App Crashes.

**Comment by jamonholmgren** [comment]
Will check this out when I can @zhigang1992 !

**Comment by squidpunch** [comment]
@jamonholmgren if you dont get to it, I can poke around too.

**Comment by jamonholmgren** [comment]
Feel free, @squidpunch !

**Comment by twerth** [comment]
I can't reproduce this. I tried it in various versions of RM. I'm using the latest RedPotion.

**Comment by squidpunch** [comment]
I'm going to try and reproduce it as well - sounds like if it works for @twerth its probably worth a `clean:all`  will report back if I can reproduce it

**Comment by squidpunch** [comment]
@zhigang1992 I just pulled the repo down and a fresh build and not seeing any issue, the error is a bit confusing because the line number in ProMotion should be referring to `@refreshable_callback` not `refreshable_callback`  are you still seeing the issue?

**Comment by zhigang1992** [comment]
Yeah, sorry I didn't make this clear, it's not crashing on build or launch. It's when you do a pull to refresh in `Open data screen` @squidpunch

**Comment by zhigang1992** [comment]
I'm still seeing this after I pull the newest changes.

**Comment by zhigang1992** [comment]
OMG. I'm sorry, I must have mistakenly removed the `@` when I'm looking through the source codes.... 
Terribly sorry for wasting all of your time. 
:sob: :sob:

**Comment by squidpunch** [comment]
@zhigang1992 I was going to ask if that might have happened!  Glad you got it sorted out :+1:
